AWSTemplateFormatVersion: '2010-09-09'
Description: PublicRead S3 bucket for lab ressources

Parameters:
  CostCenterTag:
    Description: The cost center for created resources
    Type: String
    Default: "3037"

  OwnerTag:
    Description: The name of the squad owning the resources
    Type: String
    Default: "Lab"

  AccessControl:
    Description: A canned access control list (ACL) that grants predefined permissions to the bucket.
    Type: String

  ServiceName:
    Description: A name for the bucket. The bucket name must contain only lowercase letters, numbers, periods (.), and dashes (-).
    Type: String
    Default: "Lab"

Mappings:
  ParamsByAccount:
    "457137511234":
      Account: movelab

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ServiceName
      AccessControl: !Ref AccessControl
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET]
          AllowedMethods: [HEAD]
          AllowedOrigins: ['*']
          AllowedOrigins: ['https://*']
          MaxAge: '3600'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: CostCenter
          Value: !Ref CostCenterTag
        - Key: Owner
          Value: !Ref OwnerTag
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub
              - ${arn}/*
              - { arn: !GetAtt Bucket.Arn }
          - Sid: AddPerm
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub
              - ${arn}/*
              - { arn: !GetAtt Bucket.Arn }

Outputs:
  StackName:
    Description: Stack name
    Value: !Sub ${AWS::StackName}

  WebsiteUrlSsl:
    Description: secure url where the bucket is reachable
    Value: !Sub https://${ServiceName}.s3.amazonaws.com
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteUrlSsl

  WebsiteURL:
    Description: url where the bucket is reachable
    Value: !GetAtt Bucket.WebsiteURL
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteURL

  BucketName:
    Description: Name of the bucket
    Value: !Ref ServiceName
    Export:
      Name: !Sub ${AWS::StackName}-BucketName
